Add Xbox controller support.
BarRaider/streamdeck-battery pull request #4
Opened 2022-07-24 21:38 UTC by boarder2

This PR adds support for displaying Xbox controller battery status.

It uses https://github.com/nikvoronin/XInput.Wrapper which is MIT licensed.

2022-07-28 05:10 UTC, BarRaider commented
Definitely not going to add the entire source code of XInput library into this plugin. Please use nuget to get that libeary and remove all the redundant code

2022-07-28 22:45 UTC, boarder2 commented
Good call, updated to use XInput from nuget!

2022-09-25 16:22 UTC, boarder2 commented
@BarRaider any chance at getting this in an official release?

2022-09-27 13:49 UTC, BarRaider requested changes

2022-09-27 13:49 UTC, BarRaider commented on streamdeck-battery.sln
> +# Visual Studio Version 17
Please remove the sln from your PR
No need to change the configuration settings

2022-09-27 13:49 UTC, BarRaider commented on streamdeck-battery/Actions/XboxControllerBatteryStatsAction.cs
> +            if (X.IsAvailable)
set settings.Devices to null here before checking of X is available

2022-09-27 13:49 UTC, BarRaider commented on streamdeck-battery/Actions/XboxControllerBatteryStatsAction.cs
> +            if (X.IsAvailable)
Another option (probably better), given this is just a static list, to put it as a static list of options in the html file
See here as an example:
https://github.com/BarRaider/streamdeck-wintools/blob/c7e951fd8368fb38f363a547c09629f3074c0060/streamdeck-wintools/PropertyInspector/AppAudioMixer.html#L20

2022-09-27 13:49 UTC, BarRaider commented on streamdeck-battery/PropertyInspector/XboxBattery.html
> +            <select class="sdpi-item-value select sdProperty sdList" id="devices" oninput="setSettings()" sdListTextProperty="name" sdListValueProperty="name" sdValueField="device"></select>
Consider replacing with a static list of 4 entries as per:
https://github.com/BarRaider/streamdeck-wintools/blob/c7e951fd8368fb38f363a547c09629f3074c0060/streamdeck-wintools/PropertyInspector/AppAudioMixer.html#L20

2022-09-27 13:50 UTC, BarRaider commented
Sorry, forgot about this - made some change requests, nothing major - as soon as completed I'll merge to mainline

2022-09-29 17:41 UTC, boarder2 commented on streamdeck-battery.sln
> +# Visual Studio Version 17
Removed the sln changes from the PR

2022-09-29 17:42 UTC, boarder2 commented on streamdeck-battery/Actions/XboxControllerBatteryStatsAction.cs
> +            if (X.IsAvailable)
Updated to a static list in html

2022-09-29 17:42 UTC, boarder2 commented on streamdeck-battery/PropertyInspector/XboxBattery.html
> +            <select class="sdpi-item-value select sdProperty sdList" id="devices" oninput="setSettings()" sdListTextProperty="name" sdListValueProperty="name" sdValueField="device"></select>
Updated to a static list in html

2022-09-29 17:42 UTC, boarder2 commented
Should be good to go now!

2022-10-01 17:34 UTC, BarRaider commented
Thanks for your contribution. Merging into mainline and will deploy a version on Discord very soon (https://buz.bz/d)

2022-10-01 17:34 UTC, merged